// ---ADDRESS_BOOK---
export const ADD_ADDRESS_BOOK = "ADD_ADDRESS_BOOK";
export const RETRIEVE_ADDRESS_BOOK = "RETRIEVE_ADDRESS_BOOK";
export const REMOVE_ADDRESS_BOOK_BYID = "REMOVE_ADDRESS_BOOK_BYID";
export const REMOVE_ALL_ADDRESS_BOOK = "REMOVE_ALL_ADDRESS_BOOK";
export const UPDATE_ADDRESS_BOOK_BYID = "UPDATE_ADDRESS_BOOK_BYID";

// ---AUTH---
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REFRESH_TOKEN ="REFRESH_TOKEN";

// ---MESSAGE---
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// ---COMPANY---
export const RETRIEVE_COMPANY_STR = "RETRIEVE_COMPANY_STR";
export const REMOVE_STR_COMP_ID = "REMOVE_STR_COMP_ID";
export const REMOVE_ALL_STR_COM = "REMOVE_ALL_STR_COM";
export const APPEND_STR_COM_BYID = "APPEND_STR_COM_BYID";
export const CREATE_COMPANY = "CREATE_COMPANY";
export const REMOVE_ALL_COMPANY = "REMOVE_ALL_COMPANY";
export const UPDATE_COMPANYORSTRUCTURE = "UPDATE_COMPANYORSTRUCTURE";
export const REMOVE_COMPANY_ID = "REMOVE_COMPANY_ID";

// ---Structure---
export const REMOVE_ALL_STRUCTURE = "REMOVE_ALL_STRUCTURE";
export const RETRIEVE_ALL_STR = "RETRIEVE_ALL_STR";
export const REMOVE_STRUCTURE_BYID = "REMOVE_STRUCTURE_BYID";
export const CREATE_STRUCTURE = "CREATE_STRUCTURE";
export const UPDATE_STRUCTURE_BYID = "UPDATE_STRUCTURE_BYID";

// ---User---
export const RETRIEVE_ALL_USERS ="RETRIEVE_ALL_USERS";
export const RETRIEVE_USER_BYID = "RETRIEVE_USER_BYID";
export const UPDATE_USER_BYID = "UPDATE_USER_BYID";
export const REMOVE_USER_BYID = "REMOVE_USER_BYID";
export const RETRIEVE_ROLE = "RETRIEVE_ROLE";